# 设置启用的环境

server:
  port: 80


spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondHandShopping
    username: test
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 120000
      pool-prepared-statements: false


  thymeleaf:
    cache: false


logging:
  level:
    root: warn